### ISSUE TITLE
The description of the functions in "pydoc3 primesieve" is too terse, spartan and unhelpful

### ISSUE THREAD

**Issue by shlomif** [kimwalisch/primesieve-python#42]
Hi!

After installing primesieve-python and running `pydoc3 primesieve`, I get this:

```
Help on package primesieve:

NAME
    primesieve

PACKAGE CONTENTS
    _primesieve
    numpy (package)

FUNCTIONS
    count_primes(...)
        Count prime numbers

    count_quadruplets(...)
        Count prime quadruplets

    count_quintuplets(...)
        Count prime quintuplets

    count_sextuplets(...)
        Count prime sextuplets

    count_triplets(...)
        Count prime triplets

    count_twins(...)
        Count twin primes

    get_max_stop(...)
        Returns the largest valid stop number for primesieve. 2^64-1 (UINT64_MAX)
    get_num_threads(...)
        Get the currently set number of threads

    get_sieve_size(...)
        Get the current set sieve size in KiB

    n_primes(...)

```

![Screenshot_20201017_104336](https://user-images.githubusercontent.com/3150/96331446-ed113000-1065-11eb-8f53-a0378978bfa4.png)

IMO, the functions could use a more wordy description and a useful signature (named arguments) in the documentation, and optionally some invocation samples. Also, one should mention `primesieve.Iterator()` which is completely absent.

Before I delve into the rabbit hole of finding how to better document cython functions and adding docs I wish to know if there is a general consensus that this should be fixed.

I'm using Fedora 33 beta x86-64 in case it matters.

Thanks!

**Comment by kimwalisch** [comment]
Hi shlomif,

Unfortunately I have too many open source projects and I have trouble maintaining them all. Hence my goal is to focus my efforts on my most important projects like primesieve and primecount and find contributors and/or maintainers for the other projects. primesieve-python is one of the projects where I would be happy if I found another maintainer for it.

The code quality of primesieve-python is very good as @brl0 and myself spent a significant time improving it at the beginning of this year. If you want I gladly add you as a maintainer, then you can do the changes you want. (We also need to add Python 3.9 support by updating setup.py).

When you are done doing a new release is a simple as tagging the release. This will automatically upload the new release artefacts to pypi.

**Comment by shlomif** [comment]
Hi @kimwalisch !

> Hi shlomif,
> 
> Unfortunately I have too many open source projects and I have trouble maintaining them all. Hence my goal is to focus my efforts on my most important projects like primesieve and primecount and find contributors and/or maintainers for the other projects. primesieve-python is one of the projects where I would be happy if I found another maintainer for it.
> 
> The code quality of primesieve-python is very good as @brl0 and myself spent a significant time improving it at the beginning of this year. If you want I gladly add you as a maintainer, then you can do the changes you want. (We also need to add Python 3.9 support by updating setup.py).
> 
> When you are done doing a new release is a simple as tagging the release. This will automatically upload the new release artefacts to pypi.

You can make me a maintainer if you wish and I will try to improve the docs. Thanks!

**Comment by kimwalisch** [comment]
@shlomif Do you already have a pypi account (https://pypi.org/)? What's your pypi user name?

I need to add you as a maintainer on pypi as well so that when you tag a new release the release artifacts can be uploaded automatically to https://pypi.org/project/primesieve.

**Comment by shlomif** [comment]
> @shlomif Do you already have a pypi account (https://pypi.org/)? What's your pypi user name?
> 

Yes I do, see: https://pypi.org/user/shlomif-gmail/ .

> I need to add you as a maintainer on pypi as well so that when you tag a new release the release artifacts can be uploaded automatically to https://pypi.org/project/primesieve.

Thanks!

**Comment by kimwalisch** [comment]
Thanks!

Once Travis CI support Python 3.9 I'll do a new release.
